import pandas as pd
import argparse
import random

def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate ExpandNet output against gold standard.")
    parser.add_argument("--token_file", type=str, help="Path to the token-level file (generated by expandnet).", required=True)
    parser.add_argument("--gold_file", type=str, help="Path to the gold TSV file (from BN).", required=True)
    parser.add_argument("--output_file", type=str, help="Path to the output file.", default='error_analysis_out.tsv')
    # parser.add_argument("--core_synsets", type=str, default="dependencies/corebnout.txt",
    #                     help="Path to core synsets file (default: dependencies/corebnout.txt)")
    return parser.parse_args()

args = parse_args()

goldframe = {}

with open(args.gold_file, 'r', encoding='utf-8') as f:
    for line in f:
        a, b = line.split('\t')
        assert a not in goldframe
        goldframe[a.strip()] = b.strip()

df = pd.read_csv(args.token_file, sep='\t')

def remove_zero_width_characters(s: str) -> str:
    
    ZERO_WIDTH_CHARS = [
        "\u200b",  # ZERO WIDTH SPACE
        "\u200c",  # ZERO WIDTH NON-JOINER
        "\u200d",  # ZERO WIDTH JOINER
        "\u200e",  # LEFT-TO-RIGHT MARK
        "\u200f",  # RIGHT-TO-LEFT MARK
        "\u202a",  # LEFT-TO-RIGHT EMBEDDING
        "\u202b",  # RIGHT-TO-LEFT EMBEDDING
        "\u202c",  # POP DIRECTIONAL FORMATTING
        "\u202d",  # LEFT-TO-RIGHT OVERRIDE
        "\u202e",  # RIGHT-TO-LEFT OVERRIDE
        "\ufeff",  # ZERO WIDTH NO-BREAK SPACE (BOM)
    ]
    for ch in ZERO_WIDTH_CHARS:
        s = s.replace(ch, "")
    return s

def lowercase_and_remove_zero_width(string):
    return remove_zero_width_characters(string.lower())

def in_bn(token, lemma, id, frame, dont_worry_abt_caps=True):
    if dont_worry_abt_caps:
        token = token.lower()
        lemma = lemma.lower()
        token = token.replace(' ', '_')
        lemma = lemma.replace(' ', '_')
  
    lemmas = frame[id].split()
    if token in lemmas or lemma in lemmas or (dont_worry_abt_caps and token in [l.lower() for l in lemmas]) or (dont_worry_abt_caps and lemma in [l.lower() for l in lemmas]):
        return '1', True, lemmas
    else:
        return '0', False, lemmas

df['Link in Dictionary?'] = df['Link in Dictionary?'].map(
    lambda x: 1 if str(x).strip().lower() in ['1', 'true', 't', 'yes', 'y'] else 0
)

already_done = set() 
to_write_log = []

with open(args.output_file, 'w', encoding='utf-8') as f:
  f.write('\t'.join(["English Word", "English Lemma", "Synset ID", "Translated Token",  "Translated Lemma", "Sentence ID",
                     'Source Sentence', 'Target Sentence', '(NonEmpty) Correct BN?', 'Correct BN?', 'Synset Lemmas',
                     "Token ID",  "Source POS", "Target POS" ,  
                      "Link in Dictionary?", "POS Match?",  '\n'
                     ]))
  for index, row in df.iterrows():
    assert len(row) == 12, str(len(row))
    
    if int(index) % 1000 == 0: # type: ignore
        print(f"\r{str(index)} / {str(len(df))}", end='')
    if row['Token ID'] == 'wf':
        continue
    if len(str(row['Translated Token']).strip()) == 0:
        continue
    
    
    correct, correct_b, synset_lemmas = in_bn(
        row['Translated Token'],
        row['Translated Lemma'],
        row['Synset ID'],
        goldframe
    )
    to_write = [row['Source Token'], row['Source Lemma'], row['Synset ID'], row['Translated Token'], row['Translated Lemma'],
                row['Token ID'][:9], row['Source Sentence'], row['Target Sentence'], str(int((correct_b) or len(synset_lemmas) == 0)), 
                correct, ' '.join(synset_lemmas), row['Token ID'], row['Source POS'], row['Target POS'], 
                str(int(row['Link in Dictionary?'])), str(int(row['POS Match?']))]
   
   
   
    assert correct or len(synset_lemmas) == 0
    to_write_strs = [str(a).replace('\n', '') for a in to_write]
    assert 'F' not in to_write_strs[14]
    # print(to_write_strs[7])
    assert len( to_write_strs[14]) < 2
    
    this_pair = (to_write_strs[3], to_write_strs[2])
    # print(this_pair)
    
    # print(to_write_strs[7])
   
    if str(int(row['Link in Dictionary?'])) == '1' and str(int(row['POS Match?'])) == '1' and str(int((correct_b) or len(synset_lemmas) == 0)) == '0':
        # print("Mismatch found:")
        already_done.add(this_pair)
        str_to_write = '\t'.join(to_write_strs).replace('\n', '')
        if str_to_write.count('\t') == 15:
        
            
            to_write_log.append(str_to_write + '\n')
            
  random.shuffle(to_write_log)
  print()
  for wl in to_write_log:
      f.write(wl)
    
    
            
          
           
    

